import { pipelineLabel, t } from "@/lib/i18n/th";
import { Bug, CheckCheck, Fingerprint, TriangleAlert } from "lucide-react";
import type { PipelineRun } from "@/types";

export default function CropDebugPanel({ runs }: { runs: PipelineRun[] }) {
  if (!runs.length) return null;
  const hashes = runs.filter(r => r.pipeline_id !== "hutch_full").map(r => r.crop_sha256).filter((hash): hash is string => !!hash);
  const comparable = hashes.length >= 2;
  const equal = comparable && new Set(hashes).size === 1;
  return <section className="panel mt-5" aria-label={t("Crop and Gateway debug information")}><details data-testid="technical-details"><summary className="technical-summary">{t("Advanced technical details")}</summary><div className="panel-header"><h2><Bug size={14} />{t("Input & Gateway diagnostics")}</h2>{comparable && <span className={`badge ${equal ? "success" : ""}`}>{equal ? <CheckCheck size={11} /> : <TriangleAlert size={11} />}<span>{equal ? t("Matching input") : t("Different input")}<small className="block">{equal ? t("SAME INPUT") : t("DIFFERENT INPUT")}</small></span></span>}</div><div className="panel-body"><p className="mb-4 text-[10px] leading-relaxed text-slate-400">{t("เปรียบเทียบ SHA-256 เฉพาะ Mint กับ Hutch Crop ซึ่งใช้ PNG เดียวกัน ส่วน Hutch Full ส่งภาพเต็มโดยไม่ใช้ ROI และไม่ครอบภาพ")}</p><div className="space-y-4">{runs.map(run => <details key={run.id} open className="rounded-lg border border-slate-100 p-3"><summary className="cursor-pointer text-[11px] font-semibold text-slate-600">{pipelineLabel(run.pipeline_id, run.pipeline_name)} </summary><div className="mt-3 flex gap-2"><Fingerprint size={13} className="mt-0.5 shrink-0 text-violet-400" /><code className="break-all text-[9px] text-slate-500" title="Input SHA-256">{run.input_sha256 ?? run.crop_sha256 ?? t("Crop hash unavailable")}</code></div><dl className="mt-3 grid grid-cols-[110px_1fr] gap-x-3 gap-y-2 text-[10px] text-slate-500"><dt className="text-slate-400">{t("Crop stage")}</dt><dd>{run.crop_stage ?? "—"}</dd><dt className="text-slate-400">{"ภาพต้นฉบับ / ภาพอินพุต"}</dt><dd>{run.original_width ?? "—"} × {run.original_height ?? "—"} / {run.input_width ?? run.crop_width ?? "—"} × {run.input_height ?? run.crop_height ?? "—"} px</dd><dt className="text-slate-400">{t("Encoded input")}</dt><dd>{run.input_format ?? "—"} · {run.input_byte_size?.toLocaleString() ?? "—"} {t("bytes")}</dd><dt className="text-slate-400">{t("Detector")}</dt><dd className="break-all">{run.detector_model ?? run.model_info?.detector ?? "—"}</dd><dt className="text-slate-400">{t("Recognizer")}</dt><dd className="break-all">{run.recognizer_model ?? run.model_info?.recognizer ?? "—"}</dd><dt className="text-slate-400">{t("Service / model")}</dt><dd className="break-all">{run.gateway_service ?? "—"} / {run.gateway_model ?? "—"}</dd><dt className="text-slate-400">{t("Total / Gateway")}</dt><dd>{run.processing_time_ms ?? "—"} / {run.gateway_duration_ms ?? "—"} ms</dd><dt className="text-slate-400">{t("Our request ID")}</dt><dd className="break-all font-mono">{run.request_id ?? "—"}</dd><dt className="text-slate-400">{t("Gateway request ID")}</dt><dd className="break-all font-mono">{run.gateway_request_id ?? "—"}</dd>{run.error_code && <><dt className="text-slate-400">{t("Error code")}</dt><dd className="break-all text-red-500">{run.error_code}</dd></>}</dl></details>)}</div></div></details></section>;
}
