import {test,expect} from "@playwright/test";
import type {TestCase,FieldComparison} from "../types";
import {resultPreviewBoxes} from "../lib/result-preview";

for(const width of [390,1440])test(`comparison scroll, pinned GT, modes and explicit recalculation at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});
 const evaluation={cer:0,wer:0,exact_match:true,spans:[],character_edits:0,word_edits:0,gt_characters:4,gt_words:2,normalized_ocr:"GT 1",normalized_ground_truth:"GT 1"} as FieldComparison;
 const fields=Array.from({length:8},(_,i)=>({id:`field-${i}`,field_index:i+1,roi:{x1:10,y1:10+i*20,x2:150,y2:25+i*20},source:"manual",ground_truth_raw:`GT ${i+1}`,confirmed_at:"2026-10-04"}));
 const record={id:"comparison",workflow:"global",categories:[],ground_truth_raw:"Whole GT",evaluation_mode:"per_field",layout_confirmed_at:"2026-10-04",global_fields:fields,document:{id:"doc",filename:"comparison.png",width:300,height:200,image_url:"/api/preview.svg",page_number:1},runs:Array.from({length:5},(_,i)=>({id:`run-${i}`,pipeline_id:`pipeline-${i}`,pipeline_name:`Pipeline ${i+1}`,status:"success",final_text:`Whole OCR ${i+1}`,confidence:.95,document_evaluation:{...evaluation},fields:fields.map(f=>({id:`${i}-${f.id}`,global_field_id:f.id,field_index:f.field_index,status:"success",ocr_text:`OCR ${i+1} / ${f.field_index}`,confidence:.9,evaluation:{...evaluation}}))}))} as unknown as TestCase;
 let calculations=0,failEvaluation=false;
 record.runs[1].fields![0].ocr_text="Long OCR text\n".repeat(60);
 record.runs[1].final_text="Long document result\n".repeat(100);
 record.runs[0].fields![0].diagnostics={boxes:[{bbox:[12,13,90,24],crop_bbox:[2,3,80,14],polygon:[[12,13],[90,13],[90,24],[12,24]],text:"Detected text",confidence:.92},{bbox:[92,13,140,24],text:"Second detection",confidence:.9}]};
 const mutationRequests:string[]=[];
 record.global_fields![0].ground_truth_raw="GT 1\nLine2!";
 record.runs[0].fields![0].evaluation={...evaluation,exact_match:false,normalized_ground_truth:"GT 1 Line2!",normalized_ocr:"GT 1 LineX",spans:[{kind:"equal",text:"GT 1 Line"},{kind:"substitution",text:"X",missing:"2"},{kind:"deletion",text:"",missing:"!"}]};
 record.runs[0].document_evaluation={...evaluation,exact_match:false,normalized_ground_truth:"Whole GT",normalized_ocr:"Whole G",spans:[{kind:"equal",text:"Whole G"},{kind:"deletion",text:"",missing:"T"}]} as NonNullable<typeof record.runs[0]["document_evaluation"]>;
 page.on("request",req=>{if(req.method()!=="GET")mutationRequests.push(req.url());});
 await page.route("**/api/**",async route=>{
  const req=route.request(),url=new URL(req.url()).pathname;
  if(url.endsWith("preview.svg"))return route.fulfill({contentType:"image/svg+xml",body:'<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200"><rect width="300" height="200" fill="white"/><text x="20" y="30">Preview</text></svg>'});
  if(url.endsWith("/pipelines"))return route.fulfill({json:[]}); // Historical results survive a missing config.
  if(url.endsWith("/evaluation-mode"))record.evaluation_mode=req.postDataJSON().mode;
  if(!url.includes("/global-fields/")&&url.endsWith("/ground-truth"))record.ground_truth_raw=req.postDataJSON().ground_truth_raw;
  if(url.includes("/global-fields/")&&url.endsWith("/ground-truth")){
   const field=record.global_fields!.find(f=>url.includes(f.id))!;
   field.ground_truth_raw=req.postDataJSON().ground_truth_raw;
   for(const run of record.runs)run.fields!.find(f=>f.global_field_id===field.id)!.evaluation=null;
  }
  if(url.endsWith("/evaluate")){
   calculations++;
   if(failEvaluation)return route.fulfill({status:503,json:{detail:"Evaluation failed"}});
   for(const run of record.runs)for(const field of run.fields!)field.evaluation={...evaluation};
  }
  return route.fulfill({json:record});
 });
 await page.goto("/workflow/comparison/ground-truth");
 const scroll=page.getByTestId("comparison-scroll"),first=page.getByTestId("comparison-row-field-0");
 await expect(scroll).toBeVisible();
 await expect(scroll.getByTestId("comparison-text-row")).toHaveCount(8);
 await expect(scroll.getByRole("columnheader")).toHaveCount(6);
 const requestsBeforeFilter=mutationRequests.length;
 await page.getByRole("button",{name:"กรอง Pipeline",exact:true}).click();
 await page.getByRole("checkbox",{name:"แสดง Pipeline 2",exact:true}).uncheck();
 await expect(scroll.getByRole("columnheader")).toHaveCount(6);
 await page.getByRole("button",{name:"ยกเลิก",exact:true}).click();
 await page.getByRole("button",{name:"กรอง Pipeline",exact:true}).click();
 await expect(page.getByRole("checkbox",{name:"แสดง Pipeline 2",exact:true})).toBeChecked();
 await page.getByRole("checkbox",{name:"แสดง Pipeline 2",exact:true}).uncheck();
 await page.getByRole("button",{name:"ยืนยันตัวกรอง",exact:true}).click();
 await expect(scroll.getByRole("columnheader")).toHaveCount(5);
 await expect(scroll.getByTestId("global-result-pipeline-1")).toHaveCount(0);
 await page.getByRole("button",{name:"Whole Field",exact:true}).click();
 await expect(scroll.getByTestId("global-result-pipeline-1")).toHaveCount(0);
 await page.getByRole("button",{name:"Sub-fields",exact:true}).click();
 await page.getByRole("button",{name:"กรอง Pipeline",exact:true}).click();
 await expect(page.getByRole("checkbox",{name:"แสดง Pipeline 2",exact:true})).not.toBeChecked();
 await page.getByRole("button",{name:"ซ่อนทั้งหมด",exact:true}).click();
 await page.getByRole("button",{name:"ยืนยันตัวกรอง",exact:true}).click();
 await expect(scroll.getByRole("columnheader")).toHaveCount(1);
 await expect(scroll.getByRole("rowheader")).toHaveCount(8);
 await page.getByRole("button",{name:"กรอง Pipeline",exact:true}).click();
 await page.getByRole("button",{name:"แสดงทั้งหมด",exact:true}).click();
 await page.getByRole("button",{name:"ยืนยันตัวกรอง",exact:true}).click();
 await expect(scroll.getByRole("columnheader")).toHaveCount(6);
 expect(mutationRequests.length).toBe(requestsBeforeFilter);
 await expect(first.getByTestId("global-result-pipeline-0")).toContainText("OCR 1 / 1");
 const metricPosition=await first.getByTestId("global-metrics-pipeline-0").getByRole("region",{name:"Metrics"}).boundingBox();
 const otherMetricPosition=await first.getByTestId("global-metrics-pipeline-1").getByRole("region",{name:"Metrics"}).boundingBox();
 expect(Math.abs(metricPosition!.y-otherMetricPosition!.y)).toBeLessThan(2);
 const analysisToggle=page.getByRole("button",{name:"Error Analysis Pipeline 1",exact:true});
 await analysisToggle.click();
 await page.getByRole("checkbox",{name:"HIGHLIGHT",exact:true}).check();
 await page.keyboard.press("Escape");
 const resultCell=first.getByTestId("global-result-pipeline-0");
 await expect(resultCell.getByTestId("error-analysis-line")).toHaveCount(0);
 await resultCell.getByTestId("highlight-error").filter({hasText:"X"}).click();
 await expect(page.getByText("อ่านผิด: X → ควรเป็น: 2",{exact:true})).toBeVisible();
 await page.keyboard.press("Escape");
 await resultCell.getByTestId("highlight-error").filter({hasText:"▏"}).click();
 await expect(page.getByText("ขาด: ! (อัศเจรีย์)",{exact:true})).toBeVisible();
 await page.keyboard.press("Escape");
 await analysisToggle.click();
 await page.getByRole("checkbox",{name:"Deep detail",exact:true}).check();
 await expect(page.getByRole("checkbox",{name:"HIGHLIGHT",exact:true})).toBeChecked();
 await page.keyboard.press("Escape");
 await expect(resultCell.getByTestId("highlight-correct").first()).toHaveClass(/bg-green-100/);
 await expect(resultCell.getByTestId("highlight-output")).toBeVisible();
 await expect(analysisToggle).toHaveAttribute("aria-pressed","true");
 await expect(page.getByRole("button",{name:"Error Analysis Pipeline 2",exact:true})).toHaveAttribute("aria-pressed","false");
 const analysis=first.getByTestId("global-metrics-pipeline-0").getByTestId("error-analysis-line");
 await expect(analysis).toHaveCount(2);
 await expect(analysis.nth(1)).toContainText("GT: Line2!");
 await expect(analysis.nth(1)).toContainText("OCR: LineX");
 await expect(analysis.nth(1).locator('[data-error-type="deletion"]')).toHaveClass(/comparison-span deletion/);
 await expect(analysis.nth(1)).toContainText("⟦ขาด: !⟧");
 const detailsPosition=await first.getByRole("region",{name:"Error Analysis details"}).boundingBox();
 expect(detailsPosition!.y).toBeGreaterThan(metricPosition!.y+metricPosition!.height);
 await expect(resultCell.getByTestId("global-prediction")).toHaveCount(0);
 const gtPane=await first.getByTestId("gt-pane").boundingBox();
 const ocrPane=await resultCell.getByTestId("prediction-pane").boundingBox();
 expect(Math.abs(gtPane!.height-ocrPane!.height)).toBeLessThan(2);
 expect(Math.abs(gtPane!.y-ocrPane!.y)).toBeLessThan(2);
 const afterToggle=await first.getByTestId("global-metrics-pipeline-0").getByRole("region",{name:"Metrics"}).boundingBox();
 expect(Math.abs(afterToggle!.y-metricPosition!.y)).toBeLessThan(2);
 await analysisToggle.click();
 await page.getByRole("checkbox",{name:"HIGHLIGHT",exact:true}).uncheck();
 await page.getByRole("checkbox",{name:"Deep detail",exact:true}).uncheck();
 await page.keyboard.press("Escape");
 await expect(first.getByTestId("global-result-pipeline-0").getByTestId("global-prediction")).toHaveText("OCR 1 / 1");
 const beforeRequests=mutationRequests.length;
 await expect(scroll.locator("tbody").getByRole("button",{name:/Expand/})).toHaveCount(0);
 await page.getByRole("button",{name:"Expand Pipeline 1",exact:true}).click();
 const modal=page.getByRole("dialog");
 await expect(modal).toBeVisible();
 await expect(modal.getByTestId("det-box-count")).toContainText("2");
 await expect(modal.getByTestId("expanded-field-result")).toHaveCount(8);
 if(width>=1024){const columns=modal.locator("section.lg\\:sticky").locator("..");const left=await columns.locator(":scope > section").nth(0).boundingBox();const right=await columns.locator(":scope > section").nth(1).boundingBox();expect(Math.abs(left!.width-right!.width)).toBeLessThan(2);}
 await expect(modal.getByTestId("expanded-field-result").first()).toContainText("OCR 1 / 1");
 await expect(modal.getByRole("button",{name:"แสดงกรอบ Global ทั้งหมด",exact:true})).toHaveCount(1);
 await modal.getByRole("button",{name:"Field 01",exact:true}).click();
 await expect(modal.getByTestId("document-viewer")).toHaveAttribute("data-active-field","field-0");
 await expect(modal.getByTestId("document-viewer")).toHaveAttribute("data-highlighted-det-count","2");
 await expect(modal.getByTestId("document-viewer").locator("canvas").first()).toBeVisible();
 await modal.getByRole("button",{name:"ดูกรอบ DET 1: Detected text",exact:true}).click();
 await expect(modal.getByRole("button",{name:"ดูกรอบ DET 1: Detected text",exact:true})).toHaveAttribute("aria-pressed","true");
 await page.screenshot({path:`test-results/pipeline-preview-${width}.png`,fullPage:true});
 await page.keyboard.press("Escape");await expect(modal).toHaveCount(0);
 await page.getByRole("button",{name:"Expand Pipeline 1",exact:true}).click();
 await expect(modal.getByTestId("expanded-field-result")).toHaveCount(8);
 const viewer=modal.getByTestId("document-viewer");
 await expect(viewer.locator("canvas").first()).toBeVisible();
 const scale=await viewer.getAttribute("data-view-scale");
 await modal.getByRole("button",{name:"Field 02",exact:true}).click();
 await expect(viewer).toHaveAttribute("data-active-field","field-1");
 await expect(viewer).toHaveAttribute("data-view-scale",scale!);
 await expect(modal.getByTestId("expanded-field-result").nth(1)).toHaveClass(/ring-yellow-400/);
 await page.screenshot({path:`test-results/global-yellow-preview-${width}.png`,fullPage:true});
 await modal.getByRole("button",{name:"ปิดพรีวิว Pipeline",exact:true}).click();
 await page.getByRole("button",{name:"Expand Pipeline 2",exact:true}).click();
 await expect(modal.getByTestId("det-box-count")).toContainText("ไม่มีพิกัด DET");
 await modal.getByRole("button",{name:"ปิดพรีวิว Pipeline",exact:true}).click();
 expect(mutationRequests.length).toBe(beforeRequests);
 const pinned=first.getByRole("rowheader"),before=(await pinned.boundingBox())!;
 await scroll.evaluate(e=>{e.scrollLeft=650;});
 await expect.poll(async()=>Math.abs((await pinned.boundingBox())!.x-before.x)).toBeLessThan(2);
 expect(await scroll.evaluate(e=>e.scrollWidth>e.clientWidth)).toBe(true);
 await scroll.evaluate(e=>{e.scrollTop=500;});
 expect(await scroll.evaluate(e=>e.scrollTop)).toBeGreaterThan(0);
 await page.screenshot({path:`test-results/comparison-${width}.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
 await page.getByRole("button",{name:"Whole Field",exact:true}).click();
 await expect(scroll.getByTestId("comparison-text-row")).toHaveCount(1);
 await expect(scroll.getByRole("rowheader")).toContainText("Whole GT");
 await expect(scroll.getByTestId("global-result-pipeline-0")).toContainText("Whole OCR 1");
 const wholeMetrics=await scroll.getByTestId("global-metrics-pipeline-0").getByRole("region",{name:"Metrics"}).boundingBox();
 const longMetrics=await scroll.getByTestId("global-metrics-pipeline-1").getByRole("region",{name:"Metrics"}).boundingBox();
 expect(Math.abs(wholeMetrics!.y-longMetrics!.y)).toBeLessThan(2);
 const longPane=scroll.getByTestId("global-result-pipeline-1").getByTestId("prediction-pane");
 expect(await longPane.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true);
 await analysisToggle.click();
 await page.getByRole("checkbox",{name:"Deep detail",exact:true}).check();
 await page.getByRole("checkbox",{name:"HIGHLIGHT",exact:true}).check();
 await page.keyboard.press("Escape");
 await expect(scroll.getByTestId("global-metrics-pipeline-0").locator('[data-error-type="deletion"]')).toHaveClass(/comparison-span deletion/);
 await expect(scroll.getByTestId("global-metrics-pipeline-0")).toContainText("⟦ขาด: T⟧");
 await expect(scroll.getByTestId("global-metrics-pipeline-0").getByTestId("error-analysis-line")).toContainText("GT: Whole GT");
 await page.screenshot({path:`test-results/comparison-inline-analysis-${width}.png`,fullPage:true});
 await page.getByRole("button",{name:"Sub-fields",exact:true}).click();
 expect(calculations).toBe(0);
 await page.getByRole("button",{name:"กลับไปแก้ Ground Truth"}).click();
 await expect(page.getByTestId("document-viewer").locator("canvas").first()).toBeVisible();
 await page.getByLabel("Ground Truth Field 01",{exact:true}).fill("Changed draft");
 expect(calculations).toBe(0);
 await expect(page.getByLabel("Ground Truth Field 01",{exact:true})).toHaveValue("Changed draft");
 await page.getByRole("button",{name:"บันทึก GT ฉบับร่าง",exact:true}).click();
 await expect(page.getByText("บันทึก GT ฉบับร่างแล้ว — ยังไม่ได้คำนวณผลประเมิน",{exact:true})).toBeVisible();
 expect(calculations).toBe(0);
 failEvaluation=true;
 await page.getByRole("button",{name:"ยืนยันเพื่อคำนวณ",exact:true}).click();
 await expect(page.getByTestId("workflow-ground-truth").getByRole("alert")).toBeVisible();
 await expect(scroll).toHaveCount(0);
 failEvaluation=false;
 await page.getByRole("button",{name:"ยืนยันเพื่อคำนวณ",exact:true}).click();
 await expect(first.getByTestId("global-evaluation")).toHaveCount(5);
 expect(calculations).toBe(2);
 await page.reload();
 await expect(first.getByRole("rowheader")).toContainText("Changed draft");
 await expect(first.getByTestId("global-evaluation")).toHaveCount(5);
});

test("saved detection geometry uses page coordinates once and ignores malformed boxes",()=>{
 const fields=[{id:"f",diagnostics:{boxes:[{bbox:[110,220,150,240],crop_bbox:[10,20,50,40],polygon:[[110,220],[150,220],[150,240]],text:"A"},{bbox:[1,2,0,3]},{bbox:[0,0,Infinity,10]},null]}}] as unknown as NonNullable<TestCase["runs"][number]["fields"]>;
 const boxes=resultPreviewBoxes(fields,"p");
 expect(boxes).toHaveLength(1);
 expect(boxes[0].bbox).toEqual([110,220,150,240]);
 expect(boxes[0].polygon).toEqual([[110,220],[150,220],[150,240]]);
});
